tardigrade: Update sso-admin module to use `alternate_identifier` instead of deprecated `filter`
plus3it/terraform-aws-tardigrade-sso-admin pull request #8
Opened 2023-03-14 14:38 UTC by deanp3it

updated versions.tf to use 4.4.0 for AWS, updated main.tf of account-assignment module to use alternate_identifier instead of filter

2023-03-14 14:51 UTC, deanp3it commented
@lorengordon how do you want this incremented in bumpversion?

2023-03-14 17:47 UTC, lorengordon requested changes

2023-03-14 17:47 UTC, lorengordon commented on modules/account-assignment/main.tf
> +  principal_id   = var.account_assignment.principal_type == "GROUP" ? data.aws_identitystore_group.this.alternate_identifier : data.aws_identitystore_user.this.alternate_identifier
I feel like this shouldn't change? What was the rationale for this change?

```suggestion
  principal_id   = var.account_assignment.principal_type == "GROUP" ? data.aws_identitystore_group.this[0].id : data.aws_identitystore_user.this[0].id
```

2023-03-14 17:47 UTC, lorengordon commented on modules/account-assignment/main.tf
> +  sso_instance_arn  = var.account_assignment.instance_arn != null ? var.account_assignment.instance_arn : data.aws_ssoadmin_instances.this.arns[0]
Similarly, not sure why this is changing?

```suggestion
  identity_store_id = var.account_assignment.identity_store_id != null ? var.account_assignment.identity_store_id : data.aws_ssoadmin_instances.this[0].identity_store_ids[0]
  sso_instance_arn  = var.account_assignment.instance_arn != null ? var.account_assignment.instance_arn : data.aws_ssoadmin_instances.this[0].arns[0]
```

2023-03-14 18:52 UTC, deanp3it commented on versions.tf
> +      version = ">= 4.4.0"
Fixed

2023-03-14 19:52 UTC, lorengordon reviewed
Let's go ahead and make this a major version bump. Don't forget the changelog!

2023-03-21 15:33 UTC, deanp3it commented
@lorengordon the error message I was fixing was fixed, still failing because of the API but I think it should be ready to merge.

2023-03-21 19:05 UTC, lorengordon approved these changes

2023-03-22 17:35 UTC, merged